# coding: utf-8
import pandas as pd
from sklearn import linear_model

# Helper functions
def to_perc(val):
    return "{0:.0f}%".format(val*100)


# Main functions
def read_data():
    '''
    Read data from data.xlsx and then return a dictionary
    with each key corresponding to the survey round and
    value the response rate data for that round
    '''
    xl = pd.ExcelFile('data.xlsx')
    dsets = {}
    for n in xl.sheet_names:
        dsets[n] = xl.parse(n)
    return dsets


def get_client_rr():
    '''
    Convert the dictionary object generated by read_data()
    function into a stacked csv file of all response rate
    data collected over the 8 rounds
    '''
    # Bring data in
    dsets = read_data()
    raw_collist = [
        "Client",
        "Round",
        "Week 1",
        "Week 2",
        "Week 3",
        "Week 4",
        "Week 5",
        "Week 6",
        "Final",
        "Targets",
        "#Bounces",
        "%Bounces",
    ]
    final_client_rr = pd.DataFrame(columns=raw_collist)
    for rnd, data in dsets.iteritems():
        data["Round"] = rnd
        sliced = data[raw_collist]
        final_client_rr = final_client_rr.append(sliced)
    # Then reindex
    final_client_rr = final_client_rr.reset_index(drop=True)
    # Export to CSV for use later
    final_client_rr.to_csv('client_rr_data.csv', encoding='utf-8', index=False)
    return final_client_rr


